src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/ServiceCheck.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
The ServiceCheck class doesn't reuse the tag serialization code within the Client which causes constance tags set on the client to not be included in the message. This moves the logic into the client and reuses the method that writes the messages and constant tags.
=> Updated Service Check to send constant tags

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java
Were using the NonBlockingStatsDClient to push to a statsD_exporter endpoint that prometheus picks up from. 
We've noticed that we were dropping a lot of data, although we were sending it correctly. 
Looking into it it seemed to be that the size of the packets was too big. 
Given how the message buffer gets filled up; in the case where it was getting close to the 1500 mark, the addition of the ethernet/udp headers was pushing it past the MTU size causing fragmentation.
=> Reducing buffer size to 1400

README.md
The `README.md` example for `ServiceCheck` is outdated:
- constructor is private
- `OK` is not top-level in `ServiceCheck`.
=> Use builder for ServiceCheck example

src/main/java/com/timgroup/statsd/NoOpStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDClient.java
This makes the client more straightforward to use in a Spring project as
a Bean. Spring detects methods named "close" or "shutdown" and calls
them when shutting down, see [documentation](https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/annotation/Bean.java#L243-L245).
=> Add close method to StatsDClient and extend Closeable

pom.xml
Fixes the following warnings when running `mvn clean install`:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.datadoghq:java-dogstatsd-client:jar:2.3
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-gpg-plugin is missing. @ line 116, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 96, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 104, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed …
```
=> Fix maven warnings about versions and encoding

.travis.yml, pom.xml, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java
There is an atomic compare and set loop in `Math.random` that can cause performance issues.
You can find many postings on the performance aspects of this change
http://blog.anvard.org/articles/2014/01/12/concurrent-random.html
This change requires a minimum version change from Java 1.6 to 1.7
=> Use ThreadLocalRandom vs Math.random

.travis.yml, src/main/java/com/timgroup/statsd/NoOpStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDClient.java
This is already supported in other libraries like [dogstatsd-ruby](http://www.rubydoc.info/github/DataDog/dogstatsd-ruby/Datadog/Statsd#increment-instance_method) library and it'd be nice if we can use it in java-dogstatsd-client too.
=> Support for floating-point delta in counters

README.md, pom.xml, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/DummyStatsDServer.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientPerfTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/UnixSocketTest.java
This PR adds support for submission of custom metrics through a Unix Socket on Linux.
See https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support for context and benefits.
Implementation details:
- no change in the public API, UDS mode is triggered by setting `0` as port, the socket path as `hostname`
- the send timeout is set at `100ms`. It only triggers if dogstatsd is overloaded/frozen and the socket buffer is full. The equivalent in UDP is a full reception buffer, triggering a silent packet drop
- the default behaviour of the library is to ignore all exceptions, but a custom handler can be passed. Documented the expected exceptions and their meaning
- Reduced the parallelism of NonBlockingStatsDClientPerfTest (from 20 to 10) to reduce flakes on Travis
- Added the …
=> Add UDS support

pom.xml
Ensure that the build environments that test and produce the artifact for this library are constrained to specific versions of Java. (1.7-1.8 for now)
Tests will fail if the java version isn't 1.7 or 1.8.
=> Enforce java version for build

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/UnixSocketTest.java
This helps avoiding errors when sending a lot of metrics with a low frequency.
=> unix: make timeout and buffer size configurable

src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
`client.stop()` should make sure that the client sends the lingering message appropriately, but we could check for the messages the serve has received before it's actually had a chance to listen and fully process the expected message.
=> Wait for the server to process the expected message in shutdown test

README.md
Commit b99aab9 restored compatibility with StatsD, which renders the comment invalid.
=> Remove outdated comment from readme example

pom.xml, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
Support of 3 environment variables for Client configuration:
- "DD_AGENT_HOST" used to provide the Agent hostname.
- "DD_DOGSTATSD_PORT" used to provide the DogStatsD port.
- "DD_ENTITY_ID" used to provide an identifier to the Client.
=> Add environment variables support for Client configuration

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
Before this change I see:
```
Tests run: 56, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.936 sec <<< FAILURE!
sends_gauge_entityID_from_env_and_constant_tags(com.timgroup.statsd.NonBlockingStatsDClientTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: 2
at com.timgroup.statsd.NonBlockingStatsDClient.updateTagsWithEntityID(NonBlockingStatsDClient.java:1291)
at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:632)
at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:364)
at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:238)
at com.timgroup.statsd.NonBlockingStatsDClientTest.sends_gauge_entityID_from_env_and_constant_tags(NonBlockingStatsDClientTest.java:479 …
```
=> fix entity id with constant tags

.travis.yml, pom.xml
Tests were failing as `trusty` is no longer the default image on travis and the ancient java distros were not supported. 
As a side-bonus adding some newer java versions to also make sure nothing breaks in current versions (forward-compatibility not expected to be an issue 🤞).
=> [travis-ci] trusty distribution no longer default - explicit

pom.xml
Upgrades the jnr-unixsocket dependency to 0.27, so that it uses the new version of jffi (1.2.23) which passes the MacOS notarization test.
=> Bump jnr-unixsocket to 0.27

.gitignore, CHANGELOG.md, pom.xml, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/StatsDSender.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/main/resources/version.properties, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
Adding telemetry to the client about packet sent and dropped. By default we flush the telemetry every 5s.
=> Adding dogstatsd telemetry to the client

src/main/java/com/timgroup/statsd/Message.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java, src/main/java/com/timgroup/statsd/StatsDSender.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/test/java/com/timgroup/statsd/DummyStatsDServer.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientPerfTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/RecordingErrorHandler.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
This is an adaptation of #74 by @njhill by which we take the same principles and apply them to the new client architecture to reduce the overhead of allocations on the client, and consequently on the client application.
Still WIP - a couple of things went wrong after a rebase, so a few things still pending fixes.
=> [client] reduce the number of allocations

README.md
Add documentation update to show how to configure statsd client such that metrics generated inherit pod specific tags -- based on what we see in [python's client](https://github.com/DataDog/datadogpy#origin-detection-over-udp)
[ENV variable](https://github.com/DataDog/java-dogstatsd-client/blob/28055c0b836990debd110860f19d7a7f1a335eb6/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L61) lines up
=> [Documentation Update] Container Specific Tags

src/main/java/com/timgroup/statsd/BufferPool.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java, src/main/java/com/timgroup/statsd/StatsDSender.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
The oid constructor overloading was a bit of a mess, but with a copy constructor and the builder we should have managed to keep the codebase more or less clean, and we can deprecate but keep these constructors around.
We should probably add some tests to ensure these are all 100% backward compatible and safe.
=> [java] add back support for old constructors

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
This is useful for testing, will typically be unused by customers.
=> [telemetry] allow a different remote destination for telemetry stats

README.md
The current README is misleading as `2.9.0` does not have the `NonBlockingStatsDClientBuilder` class.
Updating the version reference in the pom.xml example to `2.10.0` makes the README consistent
=> Updated version in README to latest published one

src/main/java/com/timgroup/statsd/StatsDSender.java
This PR fixes resource leak caused by ad479735. There is an executor in `StatsDSender` that was never been shutdown.
=> fix: release StatsDSender executor

src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java, src/main/java/com/timgroup/statsd/Telemetry.java
- Make the Telemetry TimerTask a daemon
- Make the StatsDProcessor Executor use daemon threads
=> Fix library shutdown 

README.md
Small update to the documentation with respect to the aggregation feature.
=> [readme] update with the new aggregation instructions

src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java
Fixes an issue with the processor shutdown; bad inheritance + previous wrong shutdown of the executor service. 
This bug could range from a non-issue to a thread leak depending on the client application. Apologies for it.
=> [processor] shutdown the executor on cue, dont leak

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
For data consistency, should aggregation be enabled we will disable sampling for counts. This is due to the fact we cannot really guarantee a constant sample rate for any given count, and there keeping track of samples could introduce statistical inconsistencies. 
The main goal of sampling was to reduce traffic on the wire anyhow, and we already achieve this by enabling aggregation so this should come at no ill effects to the user.
=> [sampling] sampling on counts to be disabled when aggregation is enabled.

src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java
Unfortunately the previous thread leak fix worked on `master` because the unneeded inherited code had already been cleaned up, but the cherry-pick didn't address that detail here.
=> [processor] remove overridden method

.circleci/config.yml, src/main/java/com/timgroup/statsd/StatsDAggregator.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java
- Let's not start the timer thread unless we have the aggregator actually enabled. 
- Ensure the scheduler is stopped when the aggregator is shut down.
=> [aggregator] fix thread leak + dont always start scheduler

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
Messages should be '\n' terminated always, using the EOL delimiter helps us understand if a metric has been truncated at the end of a payload. The server side will allow enabling a mode to drop metrics that are not properly EOL terminated to avoid processing partial metrics.
=> [messsages] all messages should be EOL terminated

pom.xml
https://github.com/jnr/jnr-unixsocket/compare/jnr-unixsocket-0.27...jnr-unixsocket-0.38.3
=> Bump jnr-unixsocket from 0.27 to 0.38.3

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/StatsDAggregator.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/StatsDAggregatorTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
This PR adds a dev-mode to the client telemetry that should better help debug metric submission, and more importantly metric aggregation. This is an initial catalog of dev-mode telemetry metrics, but more may be added in the future.
=> [telemetry] dev-mode; additional metrics for better troubleshooting

.circleci/config.yml
Permission issue break caching in CircleCI. Given that these caches
are set up exactly as documentation expects and are valid for only 15
days, they seem to be too much trouble than what they are worth. This
commit removes the cache for now until we find a better way to handle
this problem.
=> [build] Remove CircleCI caching

pom.xml
Current version of this library (v0.38+) does not work on Java 7 so this
PR bumps up the version to the highest one that supports this
compatibility matrix.
https://app.circleci.com/pipelines/github/DataDog/java-dogstatsd-client/290/workflows/6f860b8f-e89f-4c92-bf2b-fd78db48a863
```
...
Tests run: 136, Failures: 0, Errors: 0, Skipped: 40
```
=> [deps] Downgrade jnr-unixsocket dependency to 0.36

CHANGELOG.md, README.md
This release has no user-facing changes but it is required for us
to test end-to-end publishing automation to Sonatype.
Note: `pom.xml` already has version `2.12.0` set from the removal of `-SNAPSHOT` suffix.
=> [release] Preparing README and CHANGELOG for 2.12.0 release

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
Old code calculated the length of header and message body sent to statsd
using codepoints instead of raw byte UTF-8 lengths. The new code now ensures
that both of those field lengths are properly calculated using the
expected encoding.
Fixes: #148
=> Fix unicode length calculations in event strings

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/StatsDBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java, src/main/java/com/timgroup/statsd/StatsDSender.java, src/main/java/com/timgroup/statsd/StatsDThreadFactory.java, src/test/java/com/timgroup/statsd/StatsDAggregatorTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
These changes cleanup and simplify the internal threading model so that the Java tracer can upgrade to the latest level of `java-dogstatsd-client`. It also adds support for using a custom thread factory which allows the Java tracer to configure StatsD threads so they are marked as agent related threads.
List of the changes:
* Avoid creating intermediate `NonBlockingStatsDClients` via copy-constructors
because each call to `NonBlockingStatsDClient` will end up spawning threads - instead we:
* copy the current builder (to avoid side-effects)
* resolve implicit elements
* use the resolved builder to create the `NonBlockingStatsDClient` once
* Remove unused copy-constructors
* Remove intermediate thread pool, clean-up shutdown logic
* Support using a custom thread factory to spawn StatsD …
=> Cleanup internal threading

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDClient.java
From what I can tell the distribution metrics feature is no longer in beta and therefore this comment does not apply. If that is not the case please let me know. Thanks!
For context here is the [original PR](https://github.com/DataDog/java-dogstatsd-client/commit/438829071e550062db76ecafcb6ec7b5836f323d) that added these comments in.
=> Remove beta comment from recordDistributionValue

README.md
Changed `/developers/metrics/` to `/metrics/`
Removed `?tab=java` (does not seem to be working)
=> Fix links to docs in readme.md

src/main/java/com/timgroup/statsd/StatsDAggregator.java
Update client side flush interval from 3s to 2s.
Motivation: see DataDog/datadog-go#199.
=> Set client side aggregation flush interval to 2s

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientMaxPerfTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientPerfTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/StatsDTestMessage.java, src/test/java/com/timgroup/statsd/UnixSocketTest.java
This change will set aggregation for simple types by default, this would reduce the overall packet traffic to the server. The goal is to reduce the overall load on the dogstatsd client-server environments. Aggregation comes with a slight overhead on the client side, but it's clearly offset by the gains on the server side.
Please note that this PR has the effect of making metric submission with sample rates ineffectual as they make no sense in the context of metric aggregation. In practice, the metric is just aggregated and the sampling is just ignored.
=> [client] enable aggregation by default

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/StatsDAggregator.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/StatsDAggregatorTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
Removes dev mode as those metrics are useful telemetry metrics regardless and cause little overhead. 
Removing dev mode introduces a change to the public API so it will require a new major release despite minimal substantial underlying changes.
_In progress..._
=> [telemetry] remove dev mode; include dev metrics by default

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
Setting was enabled by default in #158, but this change was reverted by accident when #157 was merged.
=> Re-enable aggregation by default

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java
75df66acef added option to override sampling behavior, but we need
to expose methods used to build the client for it to be useful.
=> Fix visibility for overrideable methods

.circleci/config.yml, pom.xml, src/main/java/com/timgroup/statsd/ClientChannel.java, src/main/java/com/timgroup/statsd/DatagramClientChannel.java, src/main/java/com/timgroup/statsd/NamedPipeClientChannel.java, src/main/java/com/timgroup/statsd/NamedPipeSocketAddress.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/StatsDSender.java, src/main/java/com/timgroup/statsd/UnixDatagramClientChannel.java, src/test/java/com/timgroup/statsd/DummyLowMemStatsDServer.java, src/test/java/com/timgroup/statsd/DummyStatsDServer.java, src/test/java/com/timgroup/statsd/NamedPipeDummyStatsDServer.java, src/test/java/com/timgroup/statsd/NamedPipeTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientMaxPerfTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientPerfTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java, src/test/java/com/timgroup/statsd/UDPDummyStatsDServer.java, src/test/java/com/timgroup/statsd/UnixSocketDummyStatsDServer.java, src/test/java/com/timgroup/statsd/UnixSocketTest.java
This PR adds named pipe support for windows machines. Named pipes are similar to unix domain sockets. This PR supports submitting metrics to Datadog in Azure App Services (https://github.com/DataDog/datadog-aas-extension).
The main changes are:
* Abstracting `DatagramChannel` into the `ClientChannel` interface
* Adding a `ClientChannel` implementation for named pipes
* Adding configuration support in the builder
* Subclassing `DummyStatsD` server for testing of the 3 transport types
Unfortunately, only *existing* named pipes can be written to in pure Java. In order to create named pipes for testing, JNA is used.
=> Add named pipe support for windows

src/main/java/com/timgroup/statsd/ClientChannel.java, src/main/java/com/timgroup/statsd/DatagramClientChannel.java, src/main/java/com/timgroup/statsd/NamedPipeClientChannel.java, src/main/java/com/timgroup/statsd/UnixDatagramClientChannel.java
Client channel is an implementation detail of the client, and the method where
the channel classes are used is private. There is no need for these classes to
be public.
Modified files were added in #169 and were never released yet.
=> Remove unnecessary public

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDNonBlockingProcessor.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java, src/main/java/com/timgroup/statsd/StatsDSender.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/StatsDAggregatorTest.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
If the client was created in blocking mode, flush internal buffers and queues when `.close()` or `.stop()` are called. These methods will block until all payloads are sent.
=> Flush buffers on close

THIRDPARTY.md, gen_notice.py, src/main/resources/META-INF/NOTICE
Add a NOTICE file to the binary distribution that details license
situation for each subdirectory containing third-party code. This file
should fullfill our obligations when distributing third-party code in
the jar-with-dependencies package.
Provide a more compact overview in THIRDPARTY.md.
Add a script that was used to generate the two files above.
=> Add third-party license information

src/test/java/com/timgroup/statsd/TelemetryTest.java
`send()` is called by telemetry flush timer task on a separate thread, while getMessagesAsStrings() is called from the main test thread.
When moons align, flush task will still be running (`telemetry.stop()` only cancels future tasks), and `getMessagesAsStrings()` gets called at the same time `flush()` is calling `send()` to deliver metrics.
=> Fix concurrent modification issue

README.md
Just a small fix of a typo/copy&paste mistake in the migration guide to 3.x
=> Fix typo in migration guide to builder pattern

.circleci/config.yml, pom.xml, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/test/java/com/timgroup/statsd/TelemetryTest.java, src/test/java/com/timgroup/statsd/UnixSocketTest.java
With refactor from fb4cd25066ce6c1820dac7b439da551c648f3c35 the amount of changes necessary to make jnr-unixsocket optional at runtime is fairly small, and we don't need to rely on reflection at all.
Rest of the PR is adding tests for this scenario. UDS-related tests are adjusted to skip if UDS is not available at runtime; but everything else should run as before. A new maven profile is added that drops jnr-unixsocket from classpath only when running tests. This would be similar to how things are for our library if downstream excludes jnr-unixsocket dependency.
Latest jnr-unixsocket version, 0.38.15, appears to be backwards compatible, and can be used in-place of 0.36 which we depend on currently. To help users that want to use later version, run the test suite against a newer version as …
=> Allow jnr-unixsocket version to be overridden or excluded by downstream dependenencies

src/main/java/com/timgroup/statsd/StatsDProcessor.java
Processor thread is interrupted when the client is requested to
shutdown. That this may result in an InterruptedException is
expected, and the exception is already handled appropriately. We just
don't need to report it to he user handler, as it doesn't represent an
error condition in the code (and we don't report it in other places too).
=> Don't report the expected InterruptedException

src/main/java/com/timgroup/statsd/AlphaNumericMessage.java, src/main/java/com/timgroup/statsd/Message.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
I noticed excessive CPU usage in HashMap lookups in StatsDAggregator.
The stacks shows that the HashMap had devolved into a TreeMap which
happens after frequent hash collisions. That got me looking at the
implementations of hashCode/equals in the Message heirarchy and
this seems a likely culprit.
=> Fix Message.equals

src/main/java/com/timgroup/statsd/StatsDSender.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
After an unsuccessful write, StatsDSender would not clear the buffer before returning it to the pool. This could cause the processor to get the buffer with lim<cap, possibly failing to write to the buffer and incorrectly submitting it to the sender again with pos=0 (which results in a no-op write, because after .flip() buffer would have pos=0,lim=0).
Fixes #198
=> Clear buffers before returning them to the pool

src/test/java/com/timgroup/statsd/UnixSocketTest.java
Avoid sending too many metrics to a closed socket, to avoid a race
condition with the lastException reset.
Occasionally, two metrics will be sent to the client after the server
socket was removed. First one triggers an exception and causes the
send loop to break. Test case then resets the lastException variable,
while the client is still running and has another message buffered. If
that is delivered before the server is started, it triggers another
exception and causes nullValue() check to fail and the end of the test
case.
=> Fix UnixSocketTest#resist_dsd_restart

DEPS.md
Document possible options for jnr-unixsocket dependency while we stick with an older version to provide Java 7 support.
=> Add documentation for dependency overrides

src/main/java/com/timgroup/statsd/AlphaNumericMessage.java, src/main/java/com/timgroup/statsd/MapUtils.java, src/main/java/com/timgroup/statsd/Message.java, src/main/java/com/timgroup/statsd/StatsDAggregator.java, src/test/java/com/timgroup/statsd/StatsDAggregatorTest.java
We frequently see high overhead in message aggregation:
This PR consists of 3 parts:
1. Use `Map.putIfAbsent` to avoid doubling the work done in `Map.get` then `Map.put` (note the almost identical stack traces next to eachother). This has to be done via `MethodHandle`s but this can be greatly simplified when JDK7 support is dropped.
2. Tweak `Message` for better hashing (note the `TreeMap` frames below `HashMap` which indicate hash collisions):
* include the type in `hashCode` to avoid collisions in more cases
* Use `Arrays.hashCode` instead of `Objects.hash` for the tags because the latter triggers an IDE warning for ambiguous varargs parameters
* Remove the mutable `done` field from `equals` which can lead to memory leaks if the value changes after inserting a key into the map
* short …
=> Address message aggregation overhead

README.md
`.resolve()` is protected and can be used only from a custom builder implementation.
Fixes #209.
=> Remove broken code example

src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java
Explicit hostname was not overwritten by the environment variable even when the comment was first added.
=> Remove confusing comments on volatileAddressResolution

src/main/java/com/timgroup/statsd/StatsDSender.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
On version 2.13.0 of the client, we noticed truncation of tags when metrics are sent during restart of the datadog agent. This was narrowed down to the issue #198 which was resolved in #200. However, we are not in a position to upgrade the datadog agent to 4.2.0 at this time.
This solution backports clear buffers from #200 into v2.X branch. Ultimately, we would like to see a v2.13.1 release to resolve this.
cc @vickenty 
Cheers,
Andrew
=> clear buffers before returning to pool in v2.X

src/main/java/com/timgroup/statsd/StatsDProcessor.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
CharsetEncoder will encode messages up to full capacity of the destination buffer, and leave the data there even if the destination had insufficient capacity to encode the full payload. This can cause incomplete payloads to be sent to the agent, even though we threw an exception.
=> Don't send partial messages when the utf8 encoder overflows

README.md
The example here which demonstrates using a unix socket does not properly follow the guidance of using 0 as the port. The example as of the current revision does not work.
=> Updated readme to add working example for UDS

.circleci/config.yml, pom.xml
This PR updates the CircleCI images to use the latest version (`circleci/openjdk` images have been [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034)) and updates the JDKs being tested to use the latest LTS ones.
Currently can't use JDK 21 to build as it no longer supports source option 7.
=> Updating CircleCI to use LTS JDKs

src/main/java/com/timgroup/statsd/CgroupReader.java, src/test/java/com/timgroup/statsd/CgroupReaderTest.java
Implementation of https://github.com/DataDog/datadog-go/pull/291 but in Java
This Pull Request implements the support of Origin Detection when the container-id is unavailable from inside the application container only with cgroupv2.
It first retrieves the cgroup node path by parsing proc/self/cgroup which is formatted differently depending on the cgroup version. See https://man7.org/linux/man-pages/man7/cgroups.7.html.
The format is a list of hierarchy-ID:controller-list:cgroup-path  similar to:
0::<path>
1:name=systemd:... // only in cgroupv1
Once the path is retrieved, we retrieve the inode of /sys/fs/cgroup + <controller> + <path> where <path> is the path retrieved previously.
I am not sure how to create a dummy app that uses this library.
- Set up a cgroupv2 environment. A kind …
=> [CONTINT-1132] Send in-<inode> using the cgroup controller when container-id cannot be retrieved

src/main/java/com/timgroup/statsd/DirectStatsDClient.java, src/main/java/com/timgroup/statsd/Message.java, src/main/java/com/timgroup/statsd/NoOpDirectStatsDClient.java, src/main/java/com/timgroup/statsd/NoOpStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingDirectStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java, src/main/java/com/timgroup/statsd/Telemetry.java, src/test/java/com/timgroup/statsd/NonBlockingDirectStatsDClientTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java, src/test/java/com/timgroup/statsd/StatsDAggregatorTest.java, src/test/java/com/timgroup/statsd/StatsDTestMessage.java, src/test/java/com/timgroup/statsd/TelemetryTest.java
recordDistributionValues is similar to recordDistributionValue but it lets the client sends multiple samples in one message using dogstatsd 1.1 protocol.
Because this is a shift compared to how other methods are behaving, these methods are provided only in DirectStatsDClient which provides direct access to some low level dogstatsd protocol features.
This is recommended in high performance cases were the overhead of the statsd library might be significant and the sampling is already done by the client.
Port of https://github.com/DataDog/datadog-go/pull/296.
=> feat: Add an API to send multiple samples at once

.circleci/config.yml
Pin the image version used for the CI job, so it doesn't get updated behind the scenes with newer JDK.
=> AMLII-1487 Fix windows-opendjk12 CI job

src/main/java/com/timgroup/statsd/NonBlockingDirectStatsDClient.java, src/main/java/com/timgroup/statsd/Utf8.java, src/test/java/com/timgroup/statsd/Utf8Test.java
Intern code from Guava to compute the encoded length of an utf8 string and use
it to compute the size of the metadata for the multi valued message wihtout
allocating.
=> perf: Do not allocate when computing metadata size 

src/main/java/com/timgroup/statsd/UnixStreamClientChannel.java
We need to make sure we close the socket
file descriptors before forgetting them otherwise
we leak fds.
=> uds-stream: close unused sockets

src/main/java/com/timgroup/statsd/NoOpDirectStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingDirectStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingDirectStatsDClientTest.java
- sampling should always be disabled for distribution values with the direct client this is the whole point of being able to send multiple distribution values at once
- don't make the direct client final, users might need to have to extend it (same for the noop client)
=> direct: fix sampling and visibility issues with new direct client

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
We would like customers to be able to retrieve container tags even when DD_ENTITY_ID is set. The current behavior does not send the container-id if the entity id is set.
This PR implements the same changes seen in these PRs:
https://github.com/DataDog/datadog-go/pull/300
https://github.com/DataDog/datadogpy/pull/828
UDP support for origin detection was first introduced in `7.51` However it was difficult to use due to the [combination of settings required](https://github.com/DataDog/datadog-agent/blob/3b04f2a2e7e606e7ca2a737e231a2e3b8dfd7b59/comp/core/tagger/tagger.go#L378). With 7.54+ you can enable `DD_ORIGIN_DETECTION_UNIFIED` and it will "just work". 
After this change with `DD_ORIGIN_DETECTION_UNIFIED` users can control origin tags by simply changing the `cardinality` setting (to …
=> Origin Detection: Send both container ID and entity ID

src/main/java/com/timgroup/statsd/ClientChannel.java, src/main/java/com/timgroup/statsd/DatagramClientChannel.java, src/main/java/com/timgroup/statsd/NamedPipeClientChannel.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/NonBlockingStatsDClientBuilder.java, src/main/java/com/timgroup/statsd/UnixDatagramClientChannel.java, src/main/java/com/timgroup/statsd/UnixStreamClientChannel.java, src/test/java/com/timgroup/statsd/UnixStreamSocketTest.java
When the client is configured to use UDS via builder's address() method, the client defaulted to UDP-sized buffer.
This patch adds a method to the ClientChannel to fetch the default packet size for each transport type, and uses it in the client to pass the correct value to the processor. The maxPacketSizeBytes field of the resolved builder is reduced to only storing the user preferred configuration, if any.
=> AMLII-2058 Use correct buffer size for unix sockets

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/main/java/com/timgroup/statsd/StatsDProcessor.java
Optimize client UTF-8 encoding with hand-rolled conversion from UTF-16.
For pure ascii strings, this is much faster than using `CharsetEncoder` the way we were using it (A: 4.4.3, B: this PR).
While the encoding routine itself is slower, overall it runs on par with `String.getBytes` due to fewer allocations and less GC pressure (A: #259, B: this PR)
With a few non-ascii characters, it is a bit slower, but still outperforms `CharsetEncoder`.
vs String.getBytes()
=> AGTMETRICS-61 Optimize utf-8 encoding of payloads

src/test/java/com/timgroup/statsd/DummyStatsDServer.java, src/test/java/com/timgroup/statsd/UnixDatagramSocketDummyStatsDServer.java, src/test/java/com/timgroup/statsd/UnixSocketTest.java, src/test/java/com/timgroup/statsd/UnixStreamSocketTest.java
resist_dsd_restart for stream and datagram unix socket contained a race when testing server closed condition. Sending multiple payloads in a loop caused a situation when the "Connection refused" error was triggered twice, confusing the following step of the test that expects a different error.
jnr-unixsocket does not interrupt receive call when the server channel is closed, and successfully reads a datagram sent after the call to close.
This patch modifies the server to actually close the socket when instructed and send the test payload once to controllably trigger the error.
=> Fix races in the tests

src/main/java/com/timgroup/statsd/CgroupReader.java, src/main/java/com/timgroup/statsd/MapUtils.java, src/main/java/com/timgroup/statsd/Message.java, src/main/java/com/timgroup/statsd/StatsDClientException.java, src/test/java/com/timgroup/statsd/AggregationTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientBuilderTest.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java
No functional changes, only refactoring tests. Split some tests into separate classes, remove obsolete ones, and unify containerID-specific tests with the rest of the test cases.
=> AGTMETRICS-212 refactor tests

src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java, src/test/java/com/timgroup/statsd/NonBlockingStatsDClientBuilderTest.java
originDetectionEnabled is used to determine when to try to read container information from /proc. By that time it is already established that user did not provide a containerID explicitly, so the containerID part of the isOriginEnabled condition is always false.
=> AGTMETRICS-212 simplify origin detection logic

.gitlab-ci.yml
Old image is too old to install software from repositories. Switch to pipx because newer pip refuses to install packages globally.
=> Update maven image used in CI
